# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven in actionbranch

on:
  push:
    branches: [ main, actionbranch ]
  pull_request:
    branches: [ main, actionbranch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: list the current directory
      run: ls -lah
    - name: what is in the target folder?
      run: |
        cd target
        ls -lah
